Adds error type: MIN_TRADE_REQUIREMENT_NOT_MET
askmike/gekko pull request #1486
Opened 2017-12-15 16:40 UTC by austinlangdon

This add's the "minimum funds not available" error type from the bittrex exchange so that when this error is received, gekko doesn't continue looping/attempting to retry();. If the minimum funds aren't available, gekko shouldn't continue to retry.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds 'MIN_TRADE_REQUIREMENT_NOT_MET' error type for the bittrex exchange.

* **What is the current behavior?** (You can also link to an open issue here)
When this error is received by gekko, gekko continues to retry() ordering.

* **What is the new behavior (if this is a feature change)?**
If this error is recieved by gekko, gekko doesn't continue to retry() ordering and instead only logs it as an error. If minimum trade requirement isn't met, it doesn't make sense to continue retrying();. 

* **Other information**:

2017-12-16 05:46 UTC, askmike commented on exchanges/bittrex.js
> +        return;
would mind calling the callback function with the error here? Else Gekko never completes tracking the order.

2017-12-16 05:47 UTC, askmike requested changes
see nit.

2017-12-16 07:15 UTC, austinlangdon commented
@askmike  added in the callback

2017-12-16 16:05 UTC, greenbigfrog approved these changes

2017-12-27 07:22 UTC, austinlangdon commented
@askmike would you like this commit to be merged into develop instead of stable?

2018-01-10 18:39 UTC, greenbigfrog commented
Development normally happens against develop @austinlangdon

2018-02-01 11:21 UTC, austinlangdon commented
@greenbigfrog @askmike updated base to develop

2018-04-11 16:53 UTC, austinlangdon commented
@greenbigfrog @askmike 

is this good to be pulled?

2018-04-11 16:57 UTC, greenbigfrog commented
Mike is the one to ping in cases like this :)

2019-01-20 07:00 UTC, closed without merging