ESLint Configuration
askmike/gekko pull request #1752
Opened 2018-01-21 16:35 UTC by cmroche

I've been using this on my local development for a little while, it uses Prettier's formatting rules and and ESLINT config that seems to closely match coding styles already in use in the project.

Strictly informative, eslint is not enforced in any way through the test or submit pipelines, but tied with an IDE (ie VS code) it is pretty effective at highlighting linting issues.

2018-02-03 12:54 UTC, greenbigfrog requested changes

2018-02-03 12:54 UTC, greenbigfrog commented on .eslintrc.js
> +};
Missing newline at end of file

2018-02-03 12:54 UTC, greenbigfrog commented on .prettierrc
>  }
Missing newline at end of file

2018-04-06 09:19 UTC, VeeeneX commented
Why not use Airbnb config?

2018-07-13 02:12 UTC, closed without merging