bugfix #2548 if no strategy.historySize found, than get it from tradingAdvisor
askmike/gekko pull request #2577
Opened 2018-10-03 20:50 UTC by eusorov

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bugfix #2548

* **What is the current behavior?** (You can also link to an open issue here)
When using tulip indicators the update function is not called. see  #2548
this behavior is only in standalone mode, because no historySize is in sample-config is provided. That's why isAllowedToCheck is always undefined and this.completedWarmup is always false.

* **What is the new behavior (if this is a feature change)?**
Now checking after init() method if historySize is provided. If no than take the historySize from tradingAdvisor.

* **Other information**:
To  provide extra historySize in settings is not very convinient, it is better to have just one place in tradingAdvisor.historySize but with the option to override in settings.historySize.

2018-10-03 22:14 UTC, mark-sch commented
nice

2018-10-04 03:31 UTC, askmike commented
Great!

The difference between requiredHistory and historySize does not make sense anymore. I want to move towards only having 1 property, and it being defined in the strategy. But until that we have can use this. Thanks

2018-10-04 03:32 UTC, askmike requested changes

2018-10-04 03:32 UTC, askmike commented on plugins/tradingAdvisor/baseTradingMethod.js
> +  if (!this.requiredHistory){
Would you mind checking if it's actually undefined? This current check would also reset it if the strategy has defined it as `0`. A simple way would be to use lodash to check if requiredHistory is a number (`_.isNumber`).

2018-10-08 05:58 UTC, askmike commented
perfect, thanks!

2018-10-08 05:58 UTC, merged