add EXMO exchange
askmike/gekko pull request #2620
Opened 2018-10-31 17:44 UTC by pushistik

2018-11-01 08:34 UTC, askmike requested changes
Please update the dep in the package.json!

2018-11-01 08:34 UTC, askmike commented on package.json
> +    "crypto-js": "^3.1.9-1",
can you add this dep to gekko broker instead? Which means inside this package instead: https://github.com/askmike/gekko/blob/develop/exchange/package.json

Else people won't be able to install gekko broker as a standalone package: https://www.npmjs.com/package/gekko-broker

2018-11-01 10:17 UTC, askmike commented
Perfect, I will test this asap!

2018-11-14 11:06 UTC, askmike commented
Apologies for the delay, I'm super. busy. will hopefully look at this later this week!

2018-11-20 06:19 UTC, pushistik commented
Is any help required of me?

2018-12-02 22:05 UTC, askmike approved these changes

2018-12-02 22:05 UTC, merged

2018-12-02 22:05 UTC, askmike commented
Apologies for the delayed merge.