Mongodb adapter fixes + scanner
askmike/gekko pull request #656
Opened 2017-03-30 16:10 UTC by zeroX-tj

This works for me. The config still needs to be fixed as well as some config values for the exchange are not there when running from the ui. So i had to add a workaround for now.

2017-03-30 17:05 UTC, askmike requested changes

2017-03-30 17:05 UTC, askmike commented on core/markets/backtest.js
> +var adapter = config.adapters[config.adapter];
The config format has actually changed, you changed it to the old format.

2017-03-30 17:05 UTC, askmike commented on core/tools/dateRangeScanner.js
> +var adapter = config.adapters[config.adapter];
dito

2017-03-30 17:05 UTC, askmike commented on plugins/mongodb/scanner.js
> +                let [exchange, type] = collection.split('_');
Do you know if the node v6.0 (minimum as required by Gekko) supports this?

2017-03-31 16:43 UTC, zeroX-tj commented on plugins/mongodb/scanner.js
> +                let [exchange, type] = collection.split('_');
Works for 6.0 (tested)

2017-03-31 21:46 UTC, askmike commented
👍  I'll ping you if there are issues with mongo at some point.

2017-03-31 21:46 UTC, askmike commented
thanks a lot :)

2017-03-31 21:46 UTC, merged